server:
  servlet:
    context-path: /api

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:betoola
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

margin:
  fee:
    amount: 2